"""
Mosharrof AI: Autonomous Dynamic Tool Factory & Hot-Reload Engine
ইউজারের চাহিদানুযায়ী স্বয়ংক্রিয়ভাবে নতুন টুলস তৈরি, সেভ ও রিয়েল-টাইমে রেজিস্টার করার ক্ষমতা।
"""

import os
import sys
import importlib.util
from typing import Dict, Any, Callable

class ToolFactory:
    def __init__(self, tools_dir: str = "src/tools"):
        self.tools_dir = tools_dir
        self.registry: Dict[str, Callable] = {}
        os.makedirs(self.tools_dir, exist_ok=True)
        self._load_existing_tools()

    def _load_existing_tools(self):
        """ইকোসিস্টেম চালু হওয়ামাত্র বিদ্যমান সব টুল স্বয়ংক্রিয়ভাবে লোড করে"""
        if not os.path.exists(self.tools_dir):
            return
        for filename in os.listdir(self.tools_dir):
            if filename.endswith(".py") and not filename.startswith("__"):
                tool_name = filename[:-3]
                self._import_and_register(tool_name)

    def _import_and_register(self, tool_name: str) -> bool:
        """অ্যাপ রিস্টার্ট ছাড়াই অন-দ্য-ফ্লাই (Hot-Reload) নতুন টুল রেজিস্টার করা"""
        file_path = os.path.join(self.tools_dir, f"{tool_name}.py")
        if not os.path.exists(file_path):
            return False

        try:
            spec = importlib.util.spec_from_file_location(tool_name, file_path)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                if hasattr(module, "run"):
                    self.registry[tool_name] = module.run
                    return True
        except Exception as e:
            print(f"Error loading tool '{tool_name}': {e}")
        return False

    def create_tool(self, tool_name: str, code_body: str) -> str:
        """
        ইউজারের কথায় অন-দ্য-স্পট নতুন পাইথন টুল তৈরি করে ইকোসিস্টেমে যুক্ত করা
        """
        clean_name = tool_name.lower().strip().replace(" ", "_")
        file_path = os.path.join(self.tools_dir, f"{clean_name}.py")

        full_code = f'''"""
Mosharrof AI Dynamic Tool: {clean_name}
Auto-generated by Mosharrof Tool Factory Engine.
"""

def run(*args, **kwargs):
    {code_body}
'''
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_code)

        success = self._import_and_register(clean_name)
        if success:
            return f"টুল '{clean_name}' সফলভাবে তৈরি ও মোশারফ ইকোসিস্টেমে অ্যাক্টিভ করা হয়েছে!"
        return f"টুল '{clean_name}' কোড সেভ হয়েছে কিন্তু অন-দ্য-ফ্লাই লোডে সমস্যা।"

    def execute_tool(self, tool_name: str, *args, **kwargs) -> Any:
        """যেকোনো সক্রিয় টুল অন-ডিমান্ড চালানো"""
        clean_name = tool_name.lower().strip().replace(" ", "_")
        if clean_name in self.registry:
            return self.registry[clean_name](*args, **kwargs)
        return f"ত্রুটি: '{clean_name}' নামের কোনো টুলস বর্তমানে ইকোসিস্টেমে নেই।"

    def list_available_tools(self) -> list:
        """মোশারফের অধীনে বর্তমানে থাকা সব সক্রিয় টুলের তালিকা"""
        return list(self.registry.keys())
