"""
Mosharrof AI: Dynamic Tool Factory.

Tool creation/execution is permission-gated. Destructive operations are blocked
before generated code can be registered.
"""

import importlib.util
import os
import re
from typing import Dict, Any, Callable
from src.core.policy_engine import PolicyEngine


class ToolFactory:
    _FORBIDDEN_PATTERNS = (
        r"\bos\.remove\b", r"\bos\.unlink\b", r"\bshutil\.rmtree\b",
        r"\bPath\([^\n]*\)\.unlink\b", r"\bsubprocess\.", r"\bos\.system\b",
    )

    def __init__(self, tools_dir: str = "src/tools", policy_engine: PolicyEngine | None = None):
        self.tools_dir = tools_dir
        self.registry: Dict[str, Callable] = {}
        self.policy_engine = policy_engine or PolicyEngine()
        os.makedirs(self.tools_dir, exist_ok=True)
        self._load_existing_tools()

    def _load_existing_tools(self):
        if not os.path.exists(self.tools_dir):
            return
        for filename in os.listdir(self.tools_dir):
            if filename.endswith(".py") and not filename.startswith("__"):
                self._import_and_register(filename[:-3])

    def _import_and_register(self, tool_name: str) -> bool:
        file_path = os.path.join(self.tools_dir, f"{tool_name}.py")
        if not os.path.exists(file_path):
            return False
        try:
            spec = importlib.util.spec_from_file_location(tool_name, file_path)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                if hasattr(module, "run"):
                    self.registry[tool_name] = module.run
                    return True
        except Exception:
            return False
        return False

    def _contains_forbidden_code(self, code_body: str) -> bool:
        return any(re.search(pattern, code_body) for pattern in self._FORBIDDEN_PATTERNS)

    def create_tool(self, tool_name: str, code_body: str) -> str:
        if self.policy_engine.authorize("CREATE", scope="tool_factory")["status"] != "ALLOWED":
            return "DENIED: tool creation is not authorized."
        if self._contains_forbidden_code(code_body):
            return "DENIED: destructive or unrestricted system operations are blocked."

        clean_name = tool_name.lower().strip().replace(" ", "_")
        if not clean_name or not clean_name.replace("_", "").isalnum():
            return "DENIED: invalid tool name."

        file_path = os.path.join(self.tools_dir, f"{clean_name}.py")
        full_code = f'''"""
Mosharrof AI Dynamic Tool: {clean_name}
Generated by the Tool Factory.
"""

def run(*args, **kwargs):
    {code_body}
'''
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_code)
        if self._import_and_register(clean_name):
            return f"Tool '{clean_name}' created and registered."
        return f"Tool '{clean_name}' was saved but could not be registered."

    def execute_tool(self, tool_name: str, *args, **kwargs) -> Any:
        decision = self.policy_engine.authorize("EXECUTE", scope=f"tool:{tool_name}")
        if decision["status"] != "ALLOWED":
            return decision
        clean_name = tool_name.lower().strip().replace(" ", "_")
        if clean_name in self.registry:
            return self.registry[clean_name](*args, **kwargs)
        return f"ERROR: tool '{clean_name}' is not registered."

    def list_available_tools(self) -> list:
        return list(self.registry.keys())
