import { chromium } from "playwright";
const [url,output]=process.argv.slice(2);
if(!url||!output) throw new Error("URL/output required");
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:412,height:915},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const response=await page.goto(url,{waitUntil:"networkidle",timeout:60000});
if(!response||!response.ok()) throw new Error("Page failed: "+url);
await page.waitForTimeout(2500);
await page.screenshot({path:output,fullPage:false});
await browser.close();
